version: '3.9'

#### NETWORK ####

networks:
  media:
    driver: bridge

#### SERVICES ####

services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - media
    user: root
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
        #      - JELLYFIN_PublishedServerUrl=${IP}
    volumes:
      - /etc/localtime:/etc/localtime:ro
        #      - ${CONFIG_DIR}/jellyfin/cache:/cache
      - ${CONFIG_DIR}/jellyfin/config:/config
      - type: bind
        source: ${MEDIA_DIR}
        target: /data/media
    ports:
      - "8096:8096"
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    group_add:
      - "video"
    restart: unless-stopped
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8096/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

#### Jellyseerr - requests management for movies/shows ####

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    networks: 
      - media
    environment:
      - LOG_LEVEL=info
      - TZ=${TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_DIR}/jellyseerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    labels:
      - autoheal=true

#### Torrent client ####

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    networks:
      - media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - UMASK=022
      - WEBUI_PORT=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/data/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - 6881:6881/udp
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 6G

#### Indexer - allows you to use torrent trackers with *arr services ####

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    networks:
      - media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9696/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

#### Sonarr - library management for TV series ####

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/sonarr:/config
      - ${BASE_DIR}:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8989/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true


#### Radarr - library management for movies ####

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_DIR}/radarr:/config
      - ${BASE_DIR}:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7878/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true

#### Bazarr - manage subtitles ####

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - /data/config/bazarr:/config
      - ${BASE_DIR}:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media

#### WatchTower - automatic docker image update ####

  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 0:0
    networks: 
      - media
    volumes:
      - ${CONFIG_DIR}/recyclarr:/config
    environment:
      - TZ=${TIMEZONE}


  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Sofia
    ports:
      - "${PORT:-8191}:8191"        
    networks:
      - media

  autoheal:
    deploy:
      replicas: 1
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal
    image: willfarrell/autoheal:latest
    container_name: autoheal
    network_mode: none
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
